[bumpver]
current_version = "0.1.12"
version_file = "prellm/__init__.py"
version_pattern = "{semver}"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"prellm/__init__.py" = [
    '__version__ = "{version}"'
]
"pyproject.toml" = [
    'version = "{version}"'
]
